"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

import sys
from pathlib import Path

from setuptools import setup

# Add src directory to Python path so imports work
src_path = Path(__file__).parent / "src"
if str(src_path) not in sys.path:
    sys.path.insert(0, str(src_path))

APP = ["run_menubar_app.py"]
DATA_FILES = [
    ("zeit/core", ["src/zeit/core/conf.yml"]),
]

# Bundle CLI if it exists (built by PyInstaller before py2app)
# Supports both onefile mode (single binary) and onedir mode (directory)
cli_path = Path(__file__).parent / "dist" / "zeit"
if cli_path.exists():
    if cli_path.is_dir():
        # onedir mode: bundle the entire directory structure
        # Add the main executable
        DATA_FILES.append(("bin/zeit", [str(cli_path / "zeit")]))
        # Add _internal directory contents
        internal_dir = cli_path / "_internal"
        if internal_dir.exists():
            for item in internal_dir.rglob("*"):
                if item.is_file():
                    rel_path = item.relative_to(cli_path)
                    dest_dir = f"bin/zeit/{rel_path.parent}"
                    DATA_FILES.append((dest_dir, [str(item)]))
        print(f"Bundling CLI directory (onedir mode): {cli_path}")
    else:
        # onefile mode: single binary
        DATA_FILES.append(("bin", [str(cli_path)]))
        print(f"Bundling CLI binary (onefile mode): {cli_path}")
else:
    print(f"Warning: CLI not found at {cli_path}, will not be bundled")

OPTIONS = {
    "compressed": False,  # zlib doesn't work
    "argv_emulation": False,  # Not needed for menubar apps
    "strip": False,  # Don't strip binaries (causes issues with signed libs)
    "packages": [
        "zeit",
        "PySide6",
        "ollama",
        "mss",
        "pydantic",
        "yaml",  # pyyaml package, imported as 'yaml'
        "opik",
        "typer",
        "dotenv",
        "httpx",  # Required by ollama
        "shiboken6",  # Required by PySide6
    ],
    "includes": [
        "zeit.core",
        "zeit.cli",
        "zeit.ui",
        "zeit.processing",
        "zeit.data",
    ],
    "excludes": [
        "tkinter",
        "matplotlib",
        "scipy",
        "numpy",  # Add back if needed
        "tiktoken",  # Not directly used, causes signing issues
        # Exclude Qt developer tools (not needed for system tray)
        "PySide6.QtDesigner",
        "PySide6.QtHelp",
        "PySide6.QtQmlModels",
        "PySide6.QtQuick",
        "PySide6.QtQuickWidgets",
        "PySide6.QtUiTools",
        "PySide6.QtQuickLayouts",
        "PySide6.QtOpenGL",
        "PySide6.QtOpenGLWidgets",
        "PySide6.QtPrintSupport",
        "PySide6.scripts",  # Exclude development scripts like Linguist
    ],
    "qt_plugins": [
        "platforms",  # Need platform plugins for GUI
    ],
    "plist": {
        "CFBundleName": "Zeit",
        "CFBundleDisplayName": "Zeit",
        "CFBundleIdentifier": "co.invariante.zeit",
        "CFBundleVersion": "0.1.0",
        "CFBundleShortVersionString": "0.1.0",
        "LSUIElement": True,  # Hides app from Dock (menubar-only)
        "LSMinimumSystemVersion": "10.15",  # macOS Catalina minimum for screen recording API
        # Permission usage descriptions (shown in system dialogs)
        "NSScreenCaptureUsageDescription": (
            "Zeit needs screen recording access to capture screenshots and track your activities."
        ),
        "NSAppleEventsUsageDescription": (
            "Zeit needs automation access to detect the active window and application."
        ),
    },
}

setup(
    name="Zeit",
    version="0.1.0",
    app=APP,
    data_files=DATA_FILES,
    options={"py2app": OPTIONS},
    install_requires=[],  # Prevent setuptools from reading pyproject.toml dependencies
)
